# Generated by Django 4.2.4 on 2023-08-25 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_alter_acessorio_id_alter_categoria_id_modelo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cor",
            name="email",
        ),
    ]
