# Generated by Django 4.2.4 on 2023-08-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0004_remove_cor_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "cores"},
        ),
        migrations.RemoveField(
            model_name="cor",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="acessorio",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="cor",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(related_name="acessorios", to="garagem.acessorio"),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cor",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marca",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="capa",
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.modelo"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
